### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by pavel-gelver-fls** [BenMorris/NetArchTest#146]
Can you help me understand the current status of this project and what are its future prospects? On the one hand, I see that the last update was in 2021 and since then not a single change from @BenMorris, on the other hand, I see 
@NeVeSpl answering questions and having its own version of the library that continues and corrects Ben’s work, although there is no NuGet-package of it. I really want to use this particular library, since the existing alternatives are much worse IMO, but this is impossible in its current form, it will be impossible to convince colleagues to do this, since they will immediately notice that the project is "dead". So, will it live, and if in its current form this is impossible, then is it possible to transfer this project to someone, maybe some kind of foundation?

**Comment by BenMorris** [comment]
Hi Pavel,

The project is essentially feature complete and has been for some time, hence the lack of updates. With a project like this it can be tempting to continue stuffing features into it which can undermine the coherence and stability of code.

I wrote this back in 2018 because I really liked the [ArchUnit](https://www.archunit.org/) library for Java and there wasn't an equivalent for the .Net ecosystem. In the first year or two there were a lot of excellent contributions from people who helped to improve the stability and performance of the library. However, you do reach a point with a small and specialised library like this where the edge cases are largely resolved. It just _works_.

The forked implementations are an inevitable part of any open source project. @NeVeSpl's contributions have been invaluable and greatly appreciated, but he also wanted to rewrite the library to introduce other features that he felt would add value.

Note that in recent years, a [.Net port of ArchUnit](https://archunitnet.readthedocs.io/en/latest/) has been released by TNG (the people who wrote the original ArchUnit library). However, bear in mind that they haven't released a new version on Nuget in more than a year now. Perhaps that version is "feature complete" too?

Ben.

**Comment by raphaelmoreira** [comment]
I understand the "feature complete" policy, but in the case of a tool designed to validate .NET architecture, it will never truly be complete. With each new release, Microsoft evolves the syntax, functionalities, features, and structures, gradually making the package obsolete.
