### ISSUE TITLE
(Not)HaveDependencyOn - what does dependency mean?

### ISSUE THREAD

**Issue by timjansenortec** [BenMorris/NetArchTest#22]
Hello,

It is unclear for me what the 'dependency' parameter in HaveDependencyOn/NotHaveDependencyOn is supposed to mean.
Right now I am thinking it should be a fully quality type name, or a namespace.

Suppose we have the following situation:
type 'Somenamespace.TypeA' uses type 'Toplevelnamespace.Subnamespace.Type1'
type 'Somenamespace.TypeB' uses type 'SomeTypeWith_Toplevelnamespace_InTheName'

Then this query will fail:
types
  .That().ResideInNamespaceMatching('Somenamespace').ShouldNot()
  .HaveDependencyOn('Toplevelnamespace.Subnamespace.Type')
->FailedTypes = Somenamespace.TypeA

And this query will fail:
types
  .That().ResideInNamespaceMatching('Somenamespace').ShouldNot()
  .HaveDependencyOn('Toplevelnamespace.Subnamespace')
-> FailedTypes = Somenamespace.TypeA

And this query will fail:
types
  .That().ResideInNamespaceMatching('Somenamespace').ShouldNot()
  .HaveDependencyOn('Toplevelnamespace')
-> FailedTypes will contain Somenamespace.TypeA, but can also contain Somenamespace.TypeB which I do not expect

When I look at the code in DependencySearch.cs, most checks do something like this:
UsedType.FullName.StartsWith(dependency)
except this check:
                // Check each instruction for references to our types
                foreach (var instruction in method.Body.Instructions)
                {
                    if (instruction.Operand != null)
                    {
                        var operand = instruction.Operand.ToString();
                        var matches = results.SearchList.Where(m => operand.Contains(m)).ToArray();
                        foreach (var item in matches)
                        {
                            results.AddToFound(type, item);
                        }
                    }
                }
here we use string.Contains which results in the unexpected (?) behaviour.
maybe it is possible to do more specific checks for specific operands like so:
if (instruction.Operand is Mono.Cecil.GenericInstanceMethod)
{
    var genericInstanceMethod = instruction.Operand as Mono.Cecil.GenericInstanceMethod;
    foreach (var arg in genericInstanceMethod.GenericArguments)
    {
        if (results.SearchList.Any(m => arg.FullName.StartsWith(m)))
            results.AddToFound(type, arg.FullName);
    }
}

or maybe we should check that the operand text contains an element that starts with the dependency like so:
var operand = instruction.Operand.ToString();
var matches = results.SearchList.Where(m =>
{
    return
        operand.StartsWith(m) ||
        operand.Contains(' ' + m);
}).ToArray();
foreach (var item in matches)
{
    results.AddToFound(type, item);
}

Thanks in advance,
Tim

**Comment by BenMorris** [comment]
Hi there.

So the problem here is consistency of implementation? The dependency checking works on pattern matching. Every check should be using `StartsWith()` so you can specify a top-level namespace and catch any dependency on that namespace.

In which case, the "fix" would be on line 227 of `DependencySearch`, i.e. change the use of `Contains()` to `StartsWith()` so it is consistent with every other type of check.

This isn't that straightforward as we're checking each individual _instruction_. The formatting here makes it more difficult to separate out each individual line. For example, this is a typical instruction:

'"System.Void NetArchTest.TestStructure.Dependencies.ExampleDependency::.ctor()"'

I guess the fix here would be to split each instruction using a space separator. The  you would do a `StartsWith()` against each string. I'll have a look at implementing this when I get some time.

**Comment by timjansenortec** [comment]
yes, I think you understand the problem correctly.
I think you proposed solution would work. I think this is the same solution as my second suggestion.

It would also be nice if you expand the documentation for (Not)HaveDependencyOn a bit, to include the explanation that you put in your reply to my issue.

**Comment by BenMorris** [comment]
[Gets back from holiday]

OK - this has been fixed and checked in now. A couple of extra bits and pieces to clean up and I will release in the next couple of days.

Thanks for this,
