### ISSUE TITLE
Allow for smarter dependency resolution handling

### ISSUE THREAD

**Issue by ewassef** [BenMorris/NetArchTest#32]
In .NET Core applications, trying to utilize `HaveDependencyOn` will traverse the dependency tree and most likely throw an Exception due to non-published dlls.

Perhaps an overload allowing for ignoring NotFoundExceptions (via a list of exceptions to ignore or even simply a boolean) would suffice.

**Comment by BenMorris** [comment]
Can you provide a more concrete example? I'd like to be able to recreate the kind of issue that you're talking about. This might be happening because you are running tests against an incomplete application.

To explain, this might have come up a couple of times before. 

Issue #26 referred to errors thrown because NetArchTest could not load some types when calculating results. I could only replicate this by dropping a compuled application into a folder being scanned for types without the necessary dependencies.

Another related issue might be #11. This led to a change that allows you to specify additional directories for assembly resolution.

Let me know what specific use case you're talking about so I can figure out an appropriate solution.

**Comment by ewassef** [comment]
I am building a dotnet tool to scan our published applications for compliance. The code is trying to scan the publish folder of a.net core 2.2 app.
I guess I can create a sample if that's still unclear

**Comment by ewassef** [comment]
any additional thoughts on this?

**Comment by BenMorris** [comment]
I can only replicate this in two ways, both dealt with in previous issues:

1. If you are scanning a bunch of assemblies in a directory the `FailingTypes` property of `TestResult` will fail because the target type is not loaded into the domain that NetArchTest is running in. The 'FailingTypeNames' property was added as a workaround here (see issue #26).

2. When resolving an assembly you may not have all the dependencies present. This was fixed by allowing you to specify extra search directories in some of the `Types` methods, i.e. `InAssembly` and `InAssemblies` (see Issue #11 .

If you can send me a concrete example of this failing in some other context then we can fix it. Get in touch if you want to send some file-based examples.
