### ISSUE TITLE
ResideInNamespaceContaining for nested classes is invalid

### ISSUE THREAD

**Issue by sm-g** [BenMorris/NetArchTest#73]
```
namespace Xxx {
class Foo {
    public class Bar { }
}

}

Types.From()
   .Should()
   .NotResideInNamespaceContaining("Foo")
   .GetResult();
```

namespace of Foo.Bar is Xxx

**Comment by BenMorris** [comment]
This comes down to the implementation of `GetNamespace()` in [TypeDefinitionExtensions.cs](https://github.com/BenMorris/NetArchTest/blob/96de88d651a8682c99accb7c720bebc9d45f1e3c/src/NetArchTest.Rules/Extensions/TypeDefinitionExtensions.cs#L116).

For nested classes, it should be returning the parent class's namespace  - however, it appears to be returning the full name. This, in the example above, the namespace of `Bar` is regarded as `Xxx.Foo` rather than `Xxx`.

Fixing this [breaks a unit test](https://github.com/BenMorris/NetArchTest/blob/96de88d651a8682c99accb7c720bebc9d45f1e3c/test/NetArchTest.Rules.UnitTests/PredicateTests.cs#L846)  which is... well, incorrect as it turns out.

Nice spot. Will fix in the next release.

**Comment by NeVeSpl** [comment]
It is not that simple, because by definition nested classes do not have namespace at all. Thus it depends on us how we will interpret what namespace means for nested classes. There are two options:
- use most outer parent class's namespace - this is the most intuitive but creates a logical problem: it allows to exist more than one nested class with the same name in the given namespace
- use the full name of the parent class - this is lees intuitive, but does not have the logical problem as former

**Comment by BenMorris** [comment]
You're right that this isn't straightforward. It also risks wandering into the realm of rare edge case.

The problem is that Mono.Cecil returns a blank string for the `Namespace` property in nested classes. Therefore we have to infer _something_. 

My impulse is for this to be the _declared_ namespace, i.e. the value declared in a `namespace` statement.

For example, given the code below:

```
namespace DeclaredNamespace
{
    public class Level1
    {
        public class Level2 
        {
            public class Level3
            {
            }
        }
    }
}
```

I would expect all three classes to be regarded as part of `DeclaredNamespace` and be returned by the condition `ResideInNamespaceEndingWith("DeclaredNamespace")`.  However, in the current implementation only `Level1` would be returned. The namespaces are evaluated as follows for each of the nested classes:

| Class | Full name |
|-|-|
| Level1 | DeclaredNamespace |
| Level2 | DeclaredNamespace.Level1 |
| Level3 | DeclaredNamespace.Level1\Level2 |

Returning `DeclaredNamespace` for any nested class requires you to walk back up the type heirarchy until you arrive at a valid namespace. This would also have the potential for logical conflicts though I cannot think of a case where this would actually matter...?

In general though I am not sure if this is something we should be addressing. I am nervous about changing existing behaviour for something that is likely to be quite an edge case. I would be inclined to document the behaviour in the methods and leave this one as is.
